{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE NamedFieldPuns #-}
{-# LANGUAGE NegativeLiterals #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE TypeOperators #-}
{-# OPTIONS_GHC -fno-warn-missing-export-lists #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing #-}
{-# OPTIONS_GHC -fno-warn-unused-imports #-}
{-# OPTIONS_GHC -fno-warn-unused-matches #-}

-- | Generated by Haskell protocol buffer compiler. DO NOT EDIT!
module Opentelemetry.Proto.Profiles.V1experimental.Profiles where
import qualified Prelude as Hs
import qualified Proto3.Suite.Class as HsProtobuf
import qualified Proto3.Suite.DotProto as HsProtobufAST
import qualified Proto3.Suite.JSONPB as HsJSONPB
import Proto3.Suite.JSONPB ( (.=), (.:) )
import qualified Proto3.Suite.Types as HsProtobuf
import qualified Proto3.Wire as HsProtobuf
import qualified Proto3.Wire.Decode as HsProtobuf
    ( Parser, RawField )
import qualified Control.Applicative as Hs
import Control.Applicative ( (<*>), (<|>), (<$>) )
import qualified Control.DeepSeq as Hs
import qualified Control.Monad as Hs
import qualified Data.ByteString as Hs
import qualified Data.Coerce as Hs
import qualified Data.Int as Hs ( Int16, Int32, Int64 )
import qualified Data.List.NonEmpty as Hs ( NonEmpty(..) )
import qualified Data.Map as Hs ( Map, mapKeysMonotonic )
import qualified Data.Proxy as Proxy
import qualified Data.String as Hs ( fromString )
import qualified Data.Text.Lazy as Hs ( Text )
import qualified Data.Vector as Hs ( Vector )
import qualified Data.Word as Hs ( Word16, Word32, Word64 )
import qualified GHC.Enum as Hs
import qualified GHC.Generics as Hs
import qualified Google.Protobuf.Wrappers.Polymorphic as HsProtobuf
    ( Wrapped(..) )
import qualified Unsafe.Coerce as Hs
import qualified Opentelemetry.Proto.Profiles.V1experimental.Pprofextended
import qualified Opentelemetry.Proto.Common.V1.Common
import qualified Opentelemetry.Proto.Resource.V1.Resource
newtype ProfilesData
  = ProfilesData {profilesDataResourceProfiles :: (Hs.Vector Opentelemetry.Proto.Profiles.V1experimental.Profiles.ResourceProfiles)}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData ProfilesData)
instance (HsProtobuf.Named ProfilesData) where
  nameOf _ = Hs.fromString "ProfilesData"
instance (HsProtobuf.HasDefault ProfilesData)
instance (HsProtobuf.Message ProfilesData) where
  encodeMessage _ ProfilesData {profilesDataResourceProfiles}
    = (HsProtobuf.encodeMessageField
         (HsProtobuf.FieldNumber 1)
         ((Hs.coerce
             @(Hs.Vector Opentelemetry.Proto.Profiles.V1experimental.Profiles.ResourceProfiles)
             @(HsProtobuf.NestedVec Opentelemetry.Proto.Profiles.V1experimental.Profiles.ResourceProfiles))
            profilesDataResourceProfiles))
  decodeMessage _
    = Hs.pure ProfilesData
        <*>
          ((HsProtobuf.coerceOver
              @(HsProtobuf.NestedVec Opentelemetry.Proto.Profiles.V1experimental.Profiles.ResourceProfiles)
              @(Hs.Vector Opentelemetry.Proto.Profiles.V1experimental.Profiles.ResourceProfiles))
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)))
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1)
         (HsProtobufAST.Repeated
            (HsProtobufAST.Named (HsProtobufAST.Single "ResourceProfiles")))
         (HsProtobufAST.Single "resource_profiles") [] ""]
instance (HsJSONPB.ToJSONPB ProfilesData) where
  toJSONPB (ProfilesData f1)
    = HsJSONPB.object
        ["resource_profiles"
           .=
             ((Hs.coerce
                 @(Hs.Vector Opentelemetry.Proto.Profiles.V1experimental.Profiles.ResourceProfiles)
                 @(HsProtobuf.NestedVec Opentelemetry.Proto.Profiles.V1experimental.Profiles.ResourceProfiles))
                f1)]
  toEncodingPB (ProfilesData f1)
    = HsJSONPB.pairs
        ["resource_profiles"
           .=
             ((Hs.coerce
                 @(Hs.Vector Opentelemetry.Proto.Profiles.V1experimental.Profiles.ResourceProfiles)
                 @(HsProtobuf.NestedVec Opentelemetry.Proto.Profiles.V1experimental.Profiles.ResourceProfiles))
                f1)]
instance (HsJSONPB.FromJSONPB ProfilesData) where
  parseJSONPB
    = HsJSONPB.withObject
        "ProfilesData"
        (\ obj
           -> Hs.pure ProfilesData
                <*>
                  ((HsProtobuf.coerceOver
                      @(HsProtobuf.NestedVec Opentelemetry.Proto.Profiles.V1experimental.Profiles.ResourceProfiles)
                      @(Hs.Vector Opentelemetry.Proto.Profiles.V1experimental.Profiles.ResourceProfiles))
                     (obj .: "resource_profiles")))
instance (HsJSONPB.ToJSON ProfilesData) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON ProfilesData) where
  parseJSON = HsJSONPB.parseJSONPB
instance (HsJSONPB.ToSchema ProfilesData) where
  declareNamedSchema _
    = do let declare_resource_profiles = HsJSONPB.declareSchemaRef
         profilesDataResourceProfiles <- declare_resource_profiles
                                           Proxy.Proxy
         let _ = Hs.pure ProfilesData
                   <*>
                     ((HsProtobuf.coerceOver
                         @(HsProtobuf.NestedVec Opentelemetry.Proto.Profiles.V1experimental.Profiles.ResourceProfiles)
                         @(Hs.Vector Opentelemetry.Proto.Profiles.V1experimental.Profiles.ResourceProfiles))
                        (HsJSONPB.asProxy declare_resource_profiles))
         Hs.return
           HsJSONPB.NamedSchema
             {HsJSONPB._namedSchemaName = Hs.Just "ProfilesData",
              HsJSONPB._namedSchemaSchema = Hs.mempty
                                              {HsJSONPB._schemaParamSchema = Hs.mempty
                                                                               {HsJSONPB._paramSchemaType = Hs.Just
                                                                                                              HsJSONPB.SwaggerObject},
                                               HsJSONPB._schemaProperties = HsJSONPB.insOrdFromList
                                                                              [("resource_profiles", 
                                                                                profilesDataResourceProfiles)]}}
data ResourceProfiles
  = ResourceProfiles {resourceProfilesResource :: (Hs.Maybe Opentelemetry.Proto.Resource.V1.Resource.Resource),
                      resourceProfilesScopeProfiles :: (Hs.Vector Opentelemetry.Proto.Profiles.V1experimental.Profiles.ScopeProfiles),
                      resourceProfilesSchemaUrl :: Hs.Text}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData ResourceProfiles)
instance (HsProtobuf.Named ResourceProfiles) where
  nameOf _ = Hs.fromString "ResourceProfiles"
instance (HsProtobuf.HasDefault ResourceProfiles)
instance (HsProtobuf.Message ResourceProfiles) where
  encodeMessage
    _
    ResourceProfiles {resourceProfilesResource,
                      resourceProfilesScopeProfiles, resourceProfilesSchemaUrl}
    = Hs.mappend
        (Hs.mappend
           (HsProtobuf.encodeMessageField
              (HsProtobuf.FieldNumber 1)
              ((Hs.coerce
                  @(Hs.Maybe Opentelemetry.Proto.Resource.V1.Resource.Resource)
                  @(HsProtobuf.Nested Opentelemetry.Proto.Resource.V1.Resource.Resource))
                 resourceProfilesResource))
           (HsProtobuf.encodeMessageField
              (HsProtobuf.FieldNumber 2)
              ((Hs.coerce
                  @(Hs.Vector Opentelemetry.Proto.Profiles.V1experimental.Profiles.ScopeProfiles)
                  @(HsProtobuf.NestedVec Opentelemetry.Proto.Profiles.V1experimental.Profiles.ScopeProfiles))
                 resourceProfilesScopeProfiles)))
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 3)
           ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
              resourceProfilesSchemaUrl))
  decodeMessage _
    = Hs.pure ResourceProfiles
        <*>
          ((HsProtobuf.coerceOver
              @(HsProtobuf.Nested Opentelemetry.Proto.Resource.V1.Resource.Resource)
              @(Hs.Maybe Opentelemetry.Proto.Resource.V1.Resource.Resource))
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)))
        <*>
          ((HsProtobuf.coerceOver
              @(HsProtobuf.NestedVec Opentelemetry.Proto.Profiles.V1experimental.Profiles.ScopeProfiles)
              @(Hs.Vector Opentelemetry.Proto.Profiles.V1experimental.Profiles.ScopeProfiles))
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 2)))
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 3)))
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1)
         (HsProtobufAST.Prim
            (HsProtobufAST.Named
               (HsProtobufAST.Dots
                  (HsProtobufAST.Path
                     ("opentelemetry" Hs.:| ["proto", "resource", "v1", "Resource"])))))
         (HsProtobufAST.Single "resource") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 2)
         (HsProtobufAST.Repeated
            (HsProtobufAST.Named (HsProtobufAST.Single "ScopeProfiles")))
         (HsProtobufAST.Single "scope_profiles") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 3)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "schema_url") [] ""]
instance (HsJSONPB.ToJSONPB ResourceProfiles) where
  toJSONPB (ResourceProfiles f1 f2 f3)
    = HsJSONPB.object
        ["resource"
           .=
             ((Hs.coerce
                 @(Hs.Maybe Opentelemetry.Proto.Resource.V1.Resource.Resource)
                 @(HsProtobuf.Nested Opentelemetry.Proto.Resource.V1.Resource.Resource))
                f1),
         "scope_profiles"
           .=
             ((Hs.coerce
                 @(Hs.Vector Opentelemetry.Proto.Profiles.V1experimental.Profiles.ScopeProfiles)
                 @(HsProtobuf.NestedVec Opentelemetry.Proto.Profiles.V1experimental.Profiles.ScopeProfiles))
                f2),
         "schema_url"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3)]
  toEncodingPB (ResourceProfiles f1 f2 f3)
    = HsJSONPB.pairs
        ["resource"
           .=
             ((Hs.coerce
                 @(Hs.Maybe Opentelemetry.Proto.Resource.V1.Resource.Resource)
                 @(HsProtobuf.Nested Opentelemetry.Proto.Resource.V1.Resource.Resource))
                f1),
         "scope_profiles"
           .=
             ((Hs.coerce
                 @(Hs.Vector Opentelemetry.Proto.Profiles.V1experimental.Profiles.ScopeProfiles)
                 @(HsProtobuf.NestedVec Opentelemetry.Proto.Profiles.V1experimental.Profiles.ScopeProfiles))
                f2),
         "schema_url"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3)]
instance (HsJSONPB.FromJSONPB ResourceProfiles) where
  parseJSONPB
    = HsJSONPB.withObject
        "ResourceProfiles"
        (\ obj
           -> Hs.pure ResourceProfiles
                <*>
                  ((HsProtobuf.coerceOver
                      @(HsProtobuf.Nested Opentelemetry.Proto.Resource.V1.Resource.Resource)
                      @(Hs.Maybe Opentelemetry.Proto.Resource.V1.Resource.Resource))
                     (obj .: "resource"))
                <*>
                  ((HsProtobuf.coerceOver
                      @(HsProtobuf.NestedVec Opentelemetry.Proto.Profiles.V1experimental.Profiles.ScopeProfiles)
                      @(Hs.Vector Opentelemetry.Proto.Profiles.V1experimental.Profiles.ScopeProfiles))
                     (obj .: "scope_profiles"))
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "schema_url")))
instance (HsJSONPB.ToJSON ResourceProfiles) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON ResourceProfiles) where
  parseJSON = HsJSONPB.parseJSONPB
instance (HsJSONPB.ToSchema ResourceProfiles) where
  declareNamedSchema _
    = do let declare_resource = HsJSONPB.declareSchemaRef
         resourceProfilesResource <- declare_resource Proxy.Proxy
         let declare_scope_profiles = HsJSONPB.declareSchemaRef
         resourceProfilesScopeProfiles <- declare_scope_profiles Proxy.Proxy
         let declare_schema_url = HsJSONPB.declareSchemaRef
         resourceProfilesSchemaUrl <- declare_schema_url Proxy.Proxy
         let _ = Hs.pure ResourceProfiles
                   <*>
                     ((HsProtobuf.coerceOver
                         @(HsProtobuf.Nested Opentelemetry.Proto.Resource.V1.Resource.Resource)
                         @(Hs.Maybe Opentelemetry.Proto.Resource.V1.Resource.Resource))
                        (HsJSONPB.asProxy declare_resource))
                   <*>
                     ((HsProtobuf.coerceOver
                         @(HsProtobuf.NestedVec Opentelemetry.Proto.Profiles.V1experimental.Profiles.ScopeProfiles)
                         @(Hs.Vector Opentelemetry.Proto.Profiles.V1experimental.Profiles.ScopeProfiles))
                        (HsJSONPB.asProxy declare_scope_profiles))
                   <*>
                     ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                        (HsJSONPB.asProxy declare_schema_url))
         Hs.return
           HsJSONPB.NamedSchema
             {HsJSONPB._namedSchemaName = Hs.Just "ResourceProfiles",
              HsJSONPB._namedSchemaSchema = Hs.mempty
                                              {HsJSONPB._schemaParamSchema = Hs.mempty
                                                                               {HsJSONPB._paramSchemaType = Hs.Just
                                                                                                              HsJSONPB.SwaggerObject},
                                               HsJSONPB._schemaProperties = HsJSONPB.insOrdFromList
                                                                              [("resource", 
                                                                                resourceProfilesResource),
                                                                               ("scope_profiles", 
                                                                                resourceProfilesScopeProfiles),
                                                                               ("schema_url", 
                                                                                resourceProfilesSchemaUrl)]}}
data ScopeProfiles
  = ScopeProfiles {scopeProfilesScope :: (Hs.Maybe Opentelemetry.Proto.Common.V1.Common.InstrumentationScope),
                   scopeProfilesProfiles :: (Hs.Vector Opentelemetry.Proto.Profiles.V1experimental.Profiles.ProfileContainer),
                   scopeProfilesSchemaUrl :: Hs.Text}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData ScopeProfiles)
instance (HsProtobuf.Named ScopeProfiles) where
  nameOf _ = Hs.fromString "ScopeProfiles"
instance (HsProtobuf.HasDefault ScopeProfiles)
instance (HsProtobuf.Message ScopeProfiles) where
  encodeMessage
    _
    ScopeProfiles {scopeProfilesScope, scopeProfilesProfiles,
                   scopeProfilesSchemaUrl}
    = Hs.mappend
        (Hs.mappend
           (HsProtobuf.encodeMessageField
              (HsProtobuf.FieldNumber 1)
              ((Hs.coerce
                  @(Hs.Maybe Opentelemetry.Proto.Common.V1.Common.InstrumentationScope)
                  @(HsProtobuf.Nested Opentelemetry.Proto.Common.V1.Common.InstrumentationScope))
                 scopeProfilesScope))
           (HsProtobuf.encodeMessageField
              (HsProtobuf.FieldNumber 2)
              ((Hs.coerce
                  @(Hs.Vector Opentelemetry.Proto.Profiles.V1experimental.Profiles.ProfileContainer)
                  @(HsProtobuf.NestedVec Opentelemetry.Proto.Profiles.V1experimental.Profiles.ProfileContainer))
                 scopeProfilesProfiles)))
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 3)
           ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
              scopeProfilesSchemaUrl))
  decodeMessage _
    = Hs.pure ScopeProfiles
        <*>
          ((HsProtobuf.coerceOver
              @(HsProtobuf.Nested Opentelemetry.Proto.Common.V1.Common.InstrumentationScope)
              @(Hs.Maybe Opentelemetry.Proto.Common.V1.Common.InstrumentationScope))
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)))
        <*>
          ((HsProtobuf.coerceOver
              @(HsProtobuf.NestedVec Opentelemetry.Proto.Profiles.V1experimental.Profiles.ProfileContainer)
              @(Hs.Vector Opentelemetry.Proto.Profiles.V1experimental.Profiles.ProfileContainer))
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 2)))
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 3)))
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1)
         (HsProtobufAST.Prim
            (HsProtobufAST.Named
               (HsProtobufAST.Dots
                  (HsProtobufAST.Path
                     ("opentelemetry"
                        Hs.:| ["proto", "common", "v1", "InstrumentationScope"])))))
         (HsProtobufAST.Single "scope") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 2)
         (HsProtobufAST.Repeated
            (HsProtobufAST.Named (HsProtobufAST.Single "ProfileContainer")))
         (HsProtobufAST.Single "profiles") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 3)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "schema_url") [] ""]
instance (HsJSONPB.ToJSONPB ScopeProfiles) where
  toJSONPB (ScopeProfiles f1 f2 f3)
    = HsJSONPB.object
        ["scope"
           .=
             ((Hs.coerce
                 @(Hs.Maybe Opentelemetry.Proto.Common.V1.Common.InstrumentationScope)
                 @(HsProtobuf.Nested Opentelemetry.Proto.Common.V1.Common.InstrumentationScope))
                f1),
         "profiles"
           .=
             ((Hs.coerce
                 @(Hs.Vector Opentelemetry.Proto.Profiles.V1experimental.Profiles.ProfileContainer)
                 @(HsProtobuf.NestedVec Opentelemetry.Proto.Profiles.V1experimental.Profiles.ProfileContainer))
                f2),
         "schema_url"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3)]
  toEncodingPB (ScopeProfiles f1 f2 f3)
    = HsJSONPB.pairs
        ["scope"
           .=
             ((Hs.coerce
                 @(Hs.Maybe Opentelemetry.Proto.Common.V1.Common.InstrumentationScope)
                 @(HsProtobuf.Nested Opentelemetry.Proto.Common.V1.Common.InstrumentationScope))
                f1),
         "profiles"
           .=
             ((Hs.coerce
                 @(Hs.Vector Opentelemetry.Proto.Profiles.V1experimental.Profiles.ProfileContainer)
                 @(HsProtobuf.NestedVec Opentelemetry.Proto.Profiles.V1experimental.Profiles.ProfileContainer))
                f2),
         "schema_url"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3)]
instance (HsJSONPB.FromJSONPB ScopeProfiles) where
  parseJSONPB
    = HsJSONPB.withObject
        "ScopeProfiles"
        (\ obj
           -> Hs.pure ScopeProfiles
                <*>
                  ((HsProtobuf.coerceOver
                      @(HsProtobuf.Nested Opentelemetry.Proto.Common.V1.Common.InstrumentationScope)
                      @(Hs.Maybe Opentelemetry.Proto.Common.V1.Common.InstrumentationScope))
                     (obj .: "scope"))
                <*>
                  ((HsProtobuf.coerceOver
                      @(HsProtobuf.NestedVec Opentelemetry.Proto.Profiles.V1experimental.Profiles.ProfileContainer)
                      @(Hs.Vector Opentelemetry.Proto.Profiles.V1experimental.Profiles.ProfileContainer))
                     (obj .: "profiles"))
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "schema_url")))
instance (HsJSONPB.ToJSON ScopeProfiles) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON ScopeProfiles) where
  parseJSON = HsJSONPB.parseJSONPB
instance (HsJSONPB.ToSchema ScopeProfiles) where
  declareNamedSchema _
    = do let declare_scope = HsJSONPB.declareSchemaRef
         scopeProfilesScope <- declare_scope Proxy.Proxy
         let declare_profiles = HsJSONPB.declareSchemaRef
         scopeProfilesProfiles <- declare_profiles Proxy.Proxy
         let declare_schema_url = HsJSONPB.declareSchemaRef
         scopeProfilesSchemaUrl <- declare_schema_url Proxy.Proxy
         let _ = Hs.pure ScopeProfiles
                   <*>
                     ((HsProtobuf.coerceOver
                         @(HsProtobuf.Nested Opentelemetry.Proto.Common.V1.Common.InstrumentationScope)
                         @(Hs.Maybe Opentelemetry.Proto.Common.V1.Common.InstrumentationScope))
                        (HsJSONPB.asProxy declare_scope))
                   <*>
                     ((HsProtobuf.coerceOver
                         @(HsProtobuf.NestedVec Opentelemetry.Proto.Profiles.V1experimental.Profiles.ProfileContainer)
                         @(Hs.Vector Opentelemetry.Proto.Profiles.V1experimental.Profiles.ProfileContainer))
                        (HsJSONPB.asProxy declare_profiles))
                   <*>
                     ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                        (HsJSONPB.asProxy declare_schema_url))
         Hs.return
           HsJSONPB.NamedSchema
             {HsJSONPB._namedSchemaName = Hs.Just "ScopeProfiles",
              HsJSONPB._namedSchemaSchema = Hs.mempty
                                              {HsJSONPB._schemaParamSchema = Hs.mempty
                                                                               {HsJSONPB._paramSchemaType = Hs.Just
                                                                                                              HsJSONPB.SwaggerObject},
                                               HsJSONPB._schemaProperties = HsJSONPB.insOrdFromList
                                                                              [("scope", 
                                                                                scopeProfilesScope),
                                                                               ("profiles", 
                                                                                scopeProfilesProfiles),
                                                                               ("schema_url", 
                                                                                scopeProfilesSchemaUrl)]}}
data ProfileContainer
  = ProfileContainer {profileContainerProfileId :: Hs.ByteString,
                      profileContainerStartTimeUnixNano :: Hs.Word64,
                      profileContainerEndTimeUnixNano :: Hs.Word64,
                      profileContainerAttributes :: (Hs.Vector Opentelemetry.Proto.Common.V1.Common.KeyValue),
                      profileContainerDroppedAttributesCount :: Hs.Word32,
                      profileContainerOriginalPayloadFormat :: Hs.Text,
                      profileContainerOriginalPayload :: Hs.ByteString,
                      profileContainerProfile :: (Hs.Maybe Opentelemetry.Proto.Profiles.V1experimental.Pprofextended.Profile)}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
instance (Hs.NFData ProfileContainer)
instance (HsProtobuf.Named ProfileContainer) where
  nameOf _ = Hs.fromString "ProfileContainer"
instance (HsProtobuf.HasDefault ProfileContainer)
instance (HsProtobuf.Message ProfileContainer) where
  encodeMessage
    _
    ProfileContainer {profileContainerProfileId,
                      profileContainerStartTimeUnixNano, profileContainerEndTimeUnixNano,
                      profileContainerAttributes, profileContainerDroppedAttributesCount,
                      profileContainerOriginalPayloadFormat,
                      profileContainerOriginalPayload, profileContainerProfile}
    = Hs.mappend
        (Hs.mappend
           (Hs.mappend
              (Hs.mappend
                 (Hs.mappend
                    (Hs.mappend
                       (Hs.mappend
                          (HsProtobuf.encodeMessageField
                             (HsProtobuf.FieldNumber 1)
                             ((Hs.coerce @Hs.ByteString @(HsProtobuf.Bytes Hs.ByteString))
                                profileContainerProfileId))
                          (HsProtobuf.encodeMessageField
                             (HsProtobuf.FieldNumber 2)
                             ((Hs.coerce @Hs.Word64 @(HsProtobuf.Fixed Hs.Word64))
                                profileContainerStartTimeUnixNano)))
                       (HsProtobuf.encodeMessageField
                          (HsProtobuf.FieldNumber 3)
                          ((Hs.coerce @Hs.Word64 @(HsProtobuf.Fixed Hs.Word64))
                             profileContainerEndTimeUnixNano)))
                    (HsProtobuf.encodeMessageField
                       (HsProtobuf.FieldNumber 4)
                       ((Hs.coerce
                           @(Hs.Vector Opentelemetry.Proto.Common.V1.Common.KeyValue)
                           @(HsProtobuf.NestedVec Opentelemetry.Proto.Common.V1.Common.KeyValue))
                          profileContainerAttributes)))
                 (HsProtobuf.encodeMessageField
                    (HsProtobuf.FieldNumber 5) profileContainerDroppedAttributesCount))
              (HsProtobuf.encodeMessageField
                 (HsProtobuf.FieldNumber 6)
                 ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                    profileContainerOriginalPayloadFormat)))
           (HsProtobuf.encodeMessageField
              (HsProtobuf.FieldNumber 7)
              ((Hs.coerce @Hs.ByteString @(HsProtobuf.Bytes Hs.ByteString))
                 profileContainerOriginalPayload)))
        (HsProtobuf.encodeMessageField
           (HsProtobuf.FieldNumber 8)
           ((Hs.coerce
               @(Hs.Maybe Opentelemetry.Proto.Profiles.V1experimental.Pprofextended.Profile)
               @(HsProtobuf.Nested Opentelemetry.Proto.Profiles.V1experimental.Pprofextended.Profile))
              profileContainerProfile))
  decodeMessage _
    = Hs.pure ProfileContainer
        <*>
          ((HsProtobuf.coerceOver
              @(HsProtobuf.Bytes Hs.ByteString) @Hs.ByteString)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 1)))
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.Fixed Hs.Word64) @Hs.Word64)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 2)))
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.Fixed Hs.Word64) @Hs.Word64)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 3)))
        <*>
          ((HsProtobuf.coerceOver
              @(HsProtobuf.NestedVec Opentelemetry.Proto.Common.V1.Common.KeyValue)
              @(Hs.Vector Opentelemetry.Proto.Common.V1.Common.KeyValue))
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 4)))
        <*>
          HsProtobuf.at
            HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 5)
        <*>
          ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 6)))
        <*>
          ((HsProtobuf.coerceOver
              @(HsProtobuf.Bytes Hs.ByteString) @Hs.ByteString)
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 7)))
        <*>
          ((HsProtobuf.coerceOver
              @(HsProtobuf.Nested Opentelemetry.Proto.Profiles.V1experimental.Pprofextended.Profile)
              @(Hs.Maybe Opentelemetry.Proto.Profiles.V1experimental.Pprofextended.Profile))
             (HsProtobuf.at
                HsProtobuf.decodeMessageField (HsProtobuf.FieldNumber 8)))
  dotProto _
    = [HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 1) (HsProtobufAST.Prim HsProtobufAST.Bytes)
         (HsProtobufAST.Single "profile_id") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 2)
         (HsProtobufAST.Prim HsProtobufAST.Fixed64)
         (HsProtobufAST.Single "start_time_unix_nano") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 3)
         (HsProtobufAST.Prim HsProtobufAST.Fixed64)
         (HsProtobufAST.Single "end_time_unix_nano") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 4)
         (HsProtobufAST.Repeated
            (HsProtobufAST.Named
               (HsProtobufAST.Dots
                  (HsProtobufAST.Path
                     ("opentelemetry" Hs.:| ["proto", "common", "v1", "KeyValue"])))))
         (HsProtobufAST.Single "attributes") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 5)
         (HsProtobufAST.Prim HsProtobufAST.UInt32)
         (HsProtobufAST.Single "dropped_attributes_count") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 6)
         (HsProtobufAST.Prim HsProtobufAST.String)
         (HsProtobufAST.Single "original_payload_format") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 7) (HsProtobufAST.Prim HsProtobufAST.Bytes)
         (HsProtobufAST.Single "original_payload") [] "",
       HsProtobufAST.DotProtoField
         (HsProtobuf.FieldNumber 8)
         (HsProtobufAST.Prim
            (HsProtobufAST.Named
               (HsProtobufAST.Dots
                  (HsProtobufAST.Path
                     ("opentelemetry"
                        Hs.:| ["proto", "profiles", "v1experimental", "Profile"])))))
         (HsProtobufAST.Single "profile") [] ""]
instance (HsJSONPB.ToJSONPB ProfileContainer) where
  toJSONPB (ProfileContainer f1 f2 f3 f4 f5 f6 f7 f8)
    = HsJSONPB.object
        ["profile_id"
           .=
             ((Hs.coerce @Hs.ByteString @(HsProtobuf.Bytes Hs.ByteString)) f1),
         "start_time_unix_nano"
           .= ((Hs.coerce @Hs.Word64 @(HsProtobuf.Fixed Hs.Word64)) f2),
         "end_time_unix_nano"
           .= ((Hs.coerce @Hs.Word64 @(HsProtobuf.Fixed Hs.Word64)) f3),
         "attributes"
           .=
             ((Hs.coerce
                 @(Hs.Vector Opentelemetry.Proto.Common.V1.Common.KeyValue)
                 @(HsProtobuf.NestedVec Opentelemetry.Proto.Common.V1.Common.KeyValue))
                f4),
         "dropped_attributes_count" .= f5,
         "original_payload_format"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f6),
         "original_payload"
           .=
             ((Hs.coerce @Hs.ByteString @(HsProtobuf.Bytes Hs.ByteString)) f7),
         "profile"
           .=
             ((Hs.coerce
                 @(Hs.Maybe Opentelemetry.Proto.Profiles.V1experimental.Pprofextended.Profile)
                 @(HsProtobuf.Nested Opentelemetry.Proto.Profiles.V1experimental.Pprofextended.Profile))
                f8)]
  toEncodingPB (ProfileContainer f1 f2 f3 f4 f5 f6 f7 f8)
    = HsJSONPB.pairs
        ["profile_id"
           .=
             ((Hs.coerce @Hs.ByteString @(HsProtobuf.Bytes Hs.ByteString)) f1),
         "start_time_unix_nano"
           .= ((Hs.coerce @Hs.Word64 @(HsProtobuf.Fixed Hs.Word64)) f2),
         "end_time_unix_nano"
           .= ((Hs.coerce @Hs.Word64 @(HsProtobuf.Fixed Hs.Word64)) f3),
         "attributes"
           .=
             ((Hs.coerce
                 @(Hs.Vector Opentelemetry.Proto.Common.V1.Common.KeyValue)
                 @(HsProtobuf.NestedVec Opentelemetry.Proto.Common.V1.Common.KeyValue))
                f4),
         "dropped_attributes_count" .= f5,
         "original_payload_format"
           .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f6),
         "original_payload"
           .=
             ((Hs.coerce @Hs.ByteString @(HsProtobuf.Bytes Hs.ByteString)) f7),
         "profile"
           .=
             ((Hs.coerce
                 @(Hs.Maybe Opentelemetry.Proto.Profiles.V1experimental.Pprofextended.Profile)
                 @(HsProtobuf.Nested Opentelemetry.Proto.Profiles.V1experimental.Pprofextended.Profile))
                f8)]
instance (HsJSONPB.FromJSONPB ProfileContainer) where
  parseJSONPB
    = HsJSONPB.withObject
        "ProfileContainer"
        (\ obj
           -> Hs.pure ProfileContainer
                <*>
                  ((HsProtobuf.coerceOver
                      @(HsProtobuf.Bytes Hs.ByteString) @Hs.ByteString)
                     (obj .: "profile_id"))
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.Fixed Hs.Word64) @Hs.Word64)
                     (obj .: "start_time_unix_nano"))
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.Fixed Hs.Word64) @Hs.Word64)
                     (obj .: "end_time_unix_nano"))
                <*>
                  ((HsProtobuf.coerceOver
                      @(HsProtobuf.NestedVec Opentelemetry.Proto.Common.V1.Common.KeyValue)
                      @(Hs.Vector Opentelemetry.Proto.Common.V1.Common.KeyValue))
                     (obj .: "attributes"))
                <*> obj .: "dropped_attributes_count"
                <*>
                  ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                     (obj .: "original_payload_format"))
                <*>
                  ((HsProtobuf.coerceOver
                      @(HsProtobuf.Bytes Hs.ByteString) @Hs.ByteString)
                     (obj .: "original_payload"))
                <*>
                  ((HsProtobuf.coerceOver
                      @(HsProtobuf.Nested Opentelemetry.Proto.Profiles.V1experimental.Pprofextended.Profile)
                      @(Hs.Maybe Opentelemetry.Proto.Profiles.V1experimental.Pprofextended.Profile))
                     (obj .: "profile")))
instance (HsJSONPB.ToJSON ProfileContainer) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding
instance (HsJSONPB.FromJSON ProfileContainer) where
  parseJSON = HsJSONPB.parseJSONPB
instance (HsJSONPB.ToSchema ProfileContainer) where
  declareNamedSchema _
    = do let declare_profile_id = HsJSONPB.declareSchemaRef
         profileContainerProfileId <- declare_profile_id Proxy.Proxy
         let declare_start_time_unix_nano = HsJSONPB.declareSchemaRef
         profileContainerStartTimeUnixNano <- declare_start_time_unix_nano
                                                Proxy.Proxy
         let declare_end_time_unix_nano = HsJSONPB.declareSchemaRef
         profileContainerEndTimeUnixNano <- declare_end_time_unix_nano
                                              Proxy.Proxy
         let declare_attributes = HsJSONPB.declareSchemaRef
         profileContainerAttributes <- declare_attributes Proxy.Proxy
         let declare_dropped_attributes_count = HsJSONPB.declareSchemaRef
         profileContainerDroppedAttributesCount <- declare_dropped_attributes_count
                                                     Proxy.Proxy
         let declare_original_payload_format = HsJSONPB.declareSchemaRef
         profileContainerOriginalPayloadFormat <- declare_original_payload_format
                                                    Proxy.Proxy
         let declare_original_payload = HsJSONPB.declareSchemaRef
         profileContainerOriginalPayload <- declare_original_payload
                                              Proxy.Proxy
         let declare_profile = HsJSONPB.declareSchemaRef
         profileContainerProfile <- declare_profile Proxy.Proxy
         let _ = Hs.pure ProfileContainer
                   <*>
                     ((HsProtobuf.coerceOver
                         @(HsProtobuf.Bytes Hs.ByteString) @Hs.ByteString)
                        (HsJSONPB.asProxy declare_profile_id))
                   <*>
                     ((HsProtobuf.coerceOver @(HsProtobuf.Fixed Hs.Word64) @Hs.Word64)
                        (HsJSONPB.asProxy declare_start_time_unix_nano))
                   <*>
                     ((HsProtobuf.coerceOver @(HsProtobuf.Fixed Hs.Word64) @Hs.Word64)
                        (HsJSONPB.asProxy declare_end_time_unix_nano))
                   <*>
                     ((HsProtobuf.coerceOver
                         @(HsProtobuf.NestedVec Opentelemetry.Proto.Common.V1.Common.KeyValue)
                         @(Hs.Vector Opentelemetry.Proto.Common.V1.Common.KeyValue))
                        (HsJSONPB.asProxy declare_attributes))
                   <*> HsJSONPB.asProxy declare_dropped_attributes_count
                   <*>
                     ((HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                        (HsJSONPB.asProxy declare_original_payload_format))
                   <*>
                     ((HsProtobuf.coerceOver
                         @(HsProtobuf.Bytes Hs.ByteString) @Hs.ByteString)
                        (HsJSONPB.asProxy declare_original_payload))
                   <*>
                     ((HsProtobuf.coerceOver
                         @(HsProtobuf.Nested Opentelemetry.Proto.Profiles.V1experimental.Pprofextended.Profile)
                         @(Hs.Maybe Opentelemetry.Proto.Profiles.V1experimental.Pprofextended.Profile))
                        (HsJSONPB.asProxy declare_profile))
         Hs.return
           HsJSONPB.NamedSchema
             {HsJSONPB._namedSchemaName = Hs.Just "ProfileContainer",
              HsJSONPB._namedSchemaSchema = Hs.mempty
                                              {HsJSONPB._schemaParamSchema = Hs.mempty
                                                                               {HsJSONPB._paramSchemaType = Hs.Just
                                                                                                              HsJSONPB.SwaggerObject},
                                               HsJSONPB._schemaProperties = HsJSONPB.insOrdFromList
                                                                              [("profile_id", 
                                                                                profileContainerProfileId),
                                                                               ("start_time_unix_nano", 
                                                                                profileContainerStartTimeUnixNano),
                                                                               ("end_time_unix_nano", 
                                                                                profileContainerEndTimeUnixNano),
                                                                               ("attributes", 
                                                                                profileContainerAttributes),
                                                                               ("dropped_attributes_count", 
                                                                                profileContainerDroppedAttributesCount),
                                                                               ("original_payload_format", 
                                                                                profileContainerOriginalPayloadFormat),
                                                                               ("original_payload", 
                                                                                profileContainerOriginalPayload),
                                                                               ("profile", 
                                                                                profileContainerProfile)]}}