image:
  file: .gitpod.dockerfile

tasks:    
  - init: stack install

  - command: |
      echo "setting up postgres database"
      echo DATABASE_URL=$DATABASE_URL >> .env &&
      echo ROCKET_ADDRESS=$ROCKET_ADDRESS >> .env &&
      echo ROCKET_PORT=$ROCKET_PORT >> .env &&
      pg_start.sh &&
      diesel setup &&
      cargo build &&
      cargo run

  - command: |
      echo "installing and running stack executable with dependencies"
      (
        curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh
        curl -sSL https://get.haskellstack.org/ | sh
        stack --no-terminal build --dependencies-only
        stack install --local-bin-path=.
      )
  - command: gp await-port 8000 && gp preview $(gp url 8000)
      stack run

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod

ports:
  - port: 8000
    onOpen: open-preview