name: apitoolkit-server
version: 0.1.0.0
github: 'githubuser/apitoolkit-server'
license: BSD3
author: 'Author name here'
maintainer: 'example@example.com'
copyright: '2021 Author name here'

ghc-options:
  # For details on warnings: https://downloads.haskell.org/~ghc/master/users-guide/using-warnings.html
  # This list taken from https://medium.com/mercury-bank/enable-all-the-warnings-a0517bc081c3
  # Enable all warnings with -Weverything, then disable the ones we don’t care about
  - -Weverything
  - -Wno-missing-exported-signatures # missing-exported-signatures turns off the more strict -Wmissing-signatures. See https://ghc.haskell.org/trac/ghc/ticket/14794#ticket
  - -Wno-missing-import-lists # Requires explicit imports of _every_ function (e.g. ‘$’); too strict
  - -Wno-missed-specialisations # When GHC can’t specialize a polymorphic function. No big deal and requires fixing underlying libraries to solve.
  - -Wno-all-missed-specialisations # See missed-specialisations
  - -Wno-unsafe # Don’t use Safe Haskell warnings
  - -Wno-safe # Don’t use Safe Haskell warnings
  - -Wno-missing-local-signatures # Warning for polymorphic local bindings; nothing wrong with those.
  - -Wno-monomorphism-restriction # Don’t warn if the monomorphism restriction is used
  - -Wno-missing-safe-haskell-mode
  # - -fforce-recomp # force recompilation. Useful for seeing the result of compiling ghc with these listed options. It impacts compile time and should be disabled when not needed.
  - -Wno-orphans
  # remove the next options when possible. This is a temporary workaround
  - -Wno-unused-top-binds
  - -Wno-unused-matches
  - -Wno-missing-kind-signatures
  - -fwrite-ide-info
  - -hiedir=.hie
  # - -fllvm

default-extensions:
  - BangPatterns
  - BlockArguments
  - DataKinds
  - DeriveAnyClass
  - DeriveGeneric
  - DerivingStrategies
  - DerivingVia
  - DisambiguateRecordFields
  - ExtendedDefaultRules
  - FlexibleInstances
  - ImportQualifiedPost
  - InstanceSigs
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - FlexibleContexts
  - NoImplicitPrelude
  - OverloadedLabels
  - OverloadedLists
  - OverloadedStrings
  - PatternSynonyms
  - QuasiQuotes
  - RecordWildCards
  - StrictData
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - UndecidableInstances
  - OverloadedRecordDot
  - TemplateHaskell
  # - OverloadedRecordUpdate
  # - RebindableSyntax

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/apitoolkit-server#readme>

library:
  source-dirs: src
  dependencies:
    - colourista
    - effectful
    - effectful-core
    - monad-time-effectful
    - monad-time
    - wai-log
    - pg-transact-effectful
    - log-base
    - log-effectful
    - HaskellNet
    - Unique
    - aeson
    - aeson-qq
    - async
    - base
    - bytestring
    - base64
    - mtl
    - http-types
    - cache >= 0.1.3.0
    - case-insensitive
    - clock
    - co-log
    - co-log-core
    - containers
    - cookie
    - safe-exceptions
    - cryptonite
    - data-default
    - deriving-aeson
    - dotenv
    - envy
    - errors
    - extra
    - lucid-aria
    - fakedata
    - fmt
    - PyF
    - generic-lens
    - gogol
    - gogol-core
    - gogol-pubsub
    - hspec
    - http-api-data
    - lens
    - lens-aeson
    - lucid
    - lucid-htmx
    - lucid-hyperscript
    - lucid-svg
    - megaparsec
    - neat-interpolation
    - odd-jobs
    - optics-core
    - optics-th
    - parser-combinators
    - pg-entity
    - pg-transact
    - postgresql-migration
    - postgresql-simple
    - random
    - regex-tdfa
    - relude >= 1.2.0.0
    - resource-pool
    - resourcet
    - scientific
    - sendgrid-v3 >= 0.3.0.0
    - servant
    - servant-htmx
    - servant-lucid
    - servant-server
    - text
    - text-conversions
    - text-display
    - time
    - transformers
    - transformers-except
    - unordered-containers
    - uuid
    - valor >= 1.0.0.0
    - vector
    - wai
    - warp
    - witch
    - wreq
    - xxhash
    - yaml
    - pretty-relative-time
    - nyan-interpolation
    - pretty-simple
    - tmp-postgres
    - directory
    - githash
    - network-uri
    - hspec-expectations-json

executables:
  apitoolkit-server-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -fwrite-ide-info
      - -hiedir=.hie
      # - -O2
      # - -fPIC
    dependencies:
      - apitoolkit-server
      - relude >=1.1.0.0
    when:
      - condition: false
        other-modules: Paths_apitoolkit_server

tests:
  doctests:
    main: Main.hs
    source-dirs: test/doctests
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -fwrite-ide-info
      - -hiedir=.hie
    dependencies:
      - base
      - apitoolkit-server
      - doctest-parallel >= 0.1
      - relude >= 1.2.0.0
      - hspec
      - hspec-discover
  tests:
    main: Main.hs
    source-dirs: test/hspec
    dependencies:
      - base
      - apitoolkit-server
      - tmp-postgres
      - hspec
      - hspec-discover
      - doctest-parallel
      - relude >= 1.1.0.0
