name:                apitoolkit-server
version:             0.1.0.0
github:              "githubuser/apitoolkit-server"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

default-extensions: 
  - NoImplicitPrelude
  - DerivingStrategies
  - DataKinds
  - TypeFamilies
  - TypeOperators
  - TypeApplications
  - DataKinds
  - DerivingVia
  - DerivingStrategies
  - DeriveAnyClass
  - DeriveGeneric
  - RecordWildCards
  - QuasiQuotes
  - OverloadedStrings
  - OverloadedLists
  - ExtendedDefaultRules
  - OverloadedLabels

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/apitoolkit-server#readme>

dependencies:
- aeson
- aeson-qq
- base >= 4.7 && < 5
- base64
- co-log
- co-log-core
- deriving-aeson
- dotenv
- envy
- gogol
- gogol-core
- gogol-pubsub
- hspec
- lens 
- optics-core
- optics-th
- pg-entity
- pg-transact  
- postgresql-migration
- postgresql-simple
- postgresql-simple-named
- relude
- resource-pool
- resource-pool
- resourcet
- servant-server
- text
- time
- unordered-containers
- uuid
- vector
- wai
- warp
- raw-strings-qq
- regex-tdfa
- regex-tdfa-quasiquoter
- scientific
- async
- servant-lucid
- lucid
- lucid-htmx
- data-default-extra
- hspec-expectations-lifted
- hspec-pg-transact
- hspec-discover
- pg-entity
- pg-transact
- postgresql-simple
- resource-pool
- http-api-data
- valor >= 1.0.0.0
- containers
- cookie
- wreq
- aeson-optics
- lens-aeson
- jose
- errors
- transformers-either
- case-insensitive
library:
  source-dirs: src

executables:
  apitoolkit-server-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fwrite-ide-info                   
    - -hiedir=.hie
    dependencies:
    - base
    - apitoolkit-server
    - hspec-discover
    when:        
    - condition: false        
      other-modules: Paths_apitoolkit_server

tests:
  apitoolkit-server-test:
    main:                Test.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fwrite-ide-info                   
    - -hiedir=.hie
    dependencies:
    - base
    - apitoolkit-server
    - hspec-expectations-lifted
    - hspec-pg-transact
    - pg-entity
    - pg-transact
    - postgresql-simple
    - resource-pool
    - hspec-discover
