name: apitoolkit-server
version: 0.1.0.0
github: "githubuser/apitoolkit-server"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2021 Author name here"
language: GHC2021
spec-version: 0.36.0


ghc-options:
  - -fwrite-ide-info
  - -hiedir .hiefiles
  - "-hidir=.hifiles"
  - -threaded
  - -Weverything
  - -Werror # Treat warnings as errors
  - -fdefer-type-errors
  - -Werror=deferred-type-errors
  - -Werror=deferred-out-of-scope-variables
  - -fno-defer-typed-holes
  - -Wno-error=deprecations
  - -Wno-error=unused-packages
  - -Wno-error=missing-poly-kind-signatures
  - -Wno-missing-exported-signatures # missing-exported-signatures turns off the more strict -Wmissing-signatures. See https://ghc.haskell.org/trac/ghc/ticket/14794#ticket
  - -Wno-missing-import-lists # Requires explicit imports of _every_ function (e.g. ‘$’); too strict
  - -Wno-missed-specialisations # When GHC can’t specialize a polymorphic function. No big deal and requires fixing underlying libraries to solve.
  - -Wno-all-missed-specialisations # See missed-specialisations
  - -Wno-unsafe # Don’t use Safe Haskell warnings
  - -Wno-safe # Don’t use Safe Haskell warnings
  - -Wno-missing-local-signatures # Warning for polymorphic local bindings; nothing wrong with those.
  - -Wno-monomorphism-restriction # Don’t warn if the monomorphism restriction is used
  - -Wno-missing-safe-haskell-mode
  - -Wno-partial-fields
  - -Wno-prepositive-qualified-module
  - -Wno-missing-export-lists
  - -Wno-orphans
  # remove the next options when possible. This is a temporary workaround
  - -Wno-missing-deriving-strategies # for otlp generated files. Might move this to new package
  - -Wno-missing-role-annotations # for otlp generated files. Might move this to new package
  - -Wno-unused-matches
  - -Wno-missing-kind-signatures
  - -Wno-type-defaults
  - -rtsopts
  - -j4
  - -Wno-unused-top-binds
  - -Wno-unused-imports
  - -plugin-package hiedb-plugin -fplugin Plugin.HieDb
  # - "-prof"
  # - -g
  - "-fprof-late"
  - "-finfo-table-map"
  - "+RTS -N -A128m -n2m -RTS"

default-extensions:
  - BlockArguments
  - DataKinds
  - DerivingVia
  - DeriveAnyClass
  # - DerivingStrategies
  - DuplicateRecordFields
  - ExplicitNamespaces
  - ExtendedDefaultRules
  - LambdaCase
  - MultiWayIf
  - NoImplicitPrelude
  - OverloadedLabels
  - OverloadedLists
  - OverloadedRecordDot
  - OverloadedStrings
  - PatternSynonyms
  - QuasiQuotes
  - RoleAnnotations
  - UndecidableInstances
  - TypeFamilies
  - RecordWildCards
  - TemplateHaskell
  - AllowAmbiguousTypes

extra-source-files:
  - README.md

description: Please see the README on GitHub at <https://github.com/githubuser/apitoolkit-server#readme>

library:
  source-dirs:
    - src
  dependencies:
    - base 
    - relude >= 1.2.0.0
    - rust-interop
    - otlp
    - colourista
    - vector-algorithms
    - effectful
    - effectful-core
    - monad-time-effectful
    - wai-log
    - pg-transact-effectful
    - log-base
    - log-effectful
    - Unique
    - aeson
    - aeson-qq
    - async
    - bytestring
    - base64
    - mtl
    - base16-bytestring
    - http-types
    - cache >= 0.1.3.0
    - case-insensitive
    - clock
    - containers
    - cookie
    - safe-exceptions
    - safe
    - aeson-pretty
    - cryptonite
    - data-default
    - deriving-aeson
    - dotenv
    - envy
    - errors
    - mmark
    - extra
    - slugify
    - fmt
    - PyF
    - generic-lens
    - gogol
    - gogol-core
    - gogol-pubsub
    - hspec
    - hashtables
    - strict-containers
    - http-api-data
    - lens
    - lens-aeson
    - lucid >= 2.9.12.1
    - lucid-aria >= 0.1.0.1
    - lucid-htmx >= 0.1.0.7
    - lucid-hyperscript >= 0.1.0.2
    - lucid-svg >= 0.7.1.1
    - megaparsec
    - neat-interpolation
    - odd-jobs
    - parser-combinators
    - pg-entity
    - pg-transact
    - postgresql-migration
    - postgresql-simple
    - regex-tdfa
    - resource-pool
    - resourcet
    - scientific
    - sendgrid-v3 >= 0.3.0.0 # todo delete
    - servant
    - servant-htmx
    - servant-lucid
    - servant-server
    - text
    - text-display
    - unliftio
    - time
    - unordered-containers
    - uuid
    - valor >= 1.0.0.0
    - vector
    - wai
    - warp
    - witch
    - wreq
    - xxhash
    - pretty-relative-time
    - indexed-traversable
    - nyan-interpolation
    - pretty-simple
    - tmp-postgres
    - directory
    - githash
    - network-uri
    - hspec-expectations-json
    - scotty
    - filepath
    - http-client
    - wai-middleware-static
    - grpc-haskell
    - proto3-suite
    - proto3-wire
    - template-haskell
    - cryptohash-md5
    - hiedb-plugin

executables:
  apitoolkit-server-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -fwrite-ide-info
      - -hiedir=.hie
      # - -O2
      # - -fPIC
    dependencies:
      - apitoolkit-server
      - rust-interop
      - hiedb-plugin
      - name: relude
        version: ">= 1.2.0.0"
        mixin:
          - (Relude as Prelude)
          - ""

tests:
  doctests:
    main: Main.hs
    source-dirs: test/doctests
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -fwrite-ide-info
      - -hiedir=.hie
    dependencies:
      - base
      - apitoolkit-server
      - doctest-parallel >= 0.1
      - relude >= 1.2.0.0
      - hspec
      - hspec-discover
  tests:
    main: Main.hs
    source-dirs: test/hspec
    dependencies:
      - base
      - apitoolkit-server
      - tmp-postgres
      - hspec
      - hspec-discover
      - doctest-parallel
      - relude >= 1.2.0.0
