module.exports = {
  content: [
    './src/**/*.{html,js,hs}',
    './static/public/assets/js/charts.js',
    './static/public/assets/filtercomponent.js',
    './static/public/assets/testeditor.js',
    './static/public/assets/steps-editor.js',
    './static/public/assets/steps-assertions.js',
  ],
  safelist: [
    'group-has-[.errors:checked]/pg:block',
    'group-has-[.api-changes:checked]/pg:block',
    'group-has-[.healthcheckpings:checked]/pg:block',
    'group-has-[.multistep-api-test:checked]/pg:block',
    'group-has-[.throughput:checked]/pg:block',
    'group-has-[.error-logs:checked]/pg:block',
    'group-has-[.tm-toggle:checked]/tm:rotate-90',
    'group-has-[.tmplRadio0:checked]/md:bg-slate-100',
    'group-has-[.tmplRadio0:checked]/md:border',
    'group-has-[.tmplRadio0:checked]/md:block',
    'group-has-[.tmplRadio1:checked]/md:bg-slate-100',
    'group-has-[.tmplRadio1:checked]/md:border',
    'group-has-[.tmplRadio1:checked]/md:block',
    'group-has-[.tmplRadio2:checked]/md:bg-slate-100',
    'group-has-[.tmplRadio2:checked]/md:border',
    'group-has-[.tmplRadio2:checked]/md:block',
    'group-has-[.tmplRadio3:checked]/md:bg-slate-100',
    'group-has-[.tmplRadio3:checked]/md:border',
    'group-has-[.tmplRadio3:checked]/md:block',
    'group-has-[.tmplRadio4:checked]/md:bg-slate-100',
    'group-has-[.tmplRadio4:checked]/md:border',
    'group-has-[.tmplRadio4:checked]/md:block',

    'basis-full',
    'w-[16ch] ',
  ],
  daisyui: {
    themes: [
      'winter',
      'fantasy',
      'cmyk',
      'pastel',
      'emerald',
      {
        antdtheme: {
          'color-scheme': 'light',
          primary: '#1677ff', // Ant Design primary color
          'primary-content': '#ffffff', // White text on primary color
          secondary: '#463AA2', // Ant Design purple
          accent: '#C148AC',
          neutral: '#021431',
          'base-100': '#f8fafc', // Base background
          'base-200': '#f2f7ff',
          'base-300': '#e3e9f4',
          'base-content': '#394e6a',
          info: '#1677ff',
          success: '#81CFD1',
          warning: '#EFD7BB',
          error: '#E58B8B',
          // "--rounded-box": "0.4rem", // 2px border radius
          // "--rounded-btn": "0.4rem",
          // "--rounded-badge": "0.4rem",
          // "--tab-radius": "0.4rem",
          // "--btn-text-case": "none", // Sentence case for buttons
          // "--font-family": "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Helvetica, 'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei', SimSun, sans-serif;",
        },
      },
    ],
  },
  theme: {
    extend: {
      colors: {
        'gray-25': '#fcfcfd',
        'gray-150': '#ecedf0',
        'slate-25': '#fbfcfd',
        'slate-150': '#e9eef4',
        'slate-250': '#d6dee8',
        bgAlternate: '#F5F6FA',
        bgBase: '#FBFCFD',
        bgInverse: '#12131A',
        bgOverlay: '#FBFCFD',
        bgRaised: '#FBFCFD',
        bgSunken: '#F5F6FA',
        fillBrand: {
          strong: '#0068FF',
          weak: '#0068FF0D',
        },
        fillDisabled: '#0011661A',
        fillError: {
          strong: '#C73A3A',
          weak: '#FF4A4A0D',
        },
        fillHover: '#0015800A',
        fillInformation: {
          strong: '#1A74A8',
          weak: '#26B0FF0D',
        },
        fillInverse: {
          disabled: '#FFFFFF1F',
          weak: '#FFFFFF0F',
        },
        fillOverlay: '#000D4D73',
        fillPress: '#0011661A',
        fillSelected: '#0068FF',
        fillSuccess: {
          strong: '#067A57',
          weak: '#0ACC920D',
        },
        fillWarning: {
          strong: '#8F6C1A',
          weak: '#FFC02E0D',
        },
        fillWeak: '#0015800A',
        fillWeaker: '#00158005',
        fillWhite: '#FFFFFF',
        fillYellow: '#FEC62E',
        iconBrand: '#0068FFCC',
        iconDisabled: '#0011661A',
        iconError: '#C73A3ACC',
        iconInformation: '#1A74A8CC',
        iconInverse: {
          DEFAULT: '#FFFFFF99',
          disabled: '#FFFFFF1F',
          strong: '#FFFFFF',
        },
        iconNeutral: '#000D4D73',
        iconSuccess: '#067A57CC',
        iconWarning: '#8F6C1ACC',
        strokeBrand: {
          strong: '#0068FFCC',
          weak: '#0068FF33',
        },
        strokeDisabled: '#0011661A',
        strokeError: {
          strong: '#C73A3ACC',
          weak: '#C73A3A24',
        },
        strokeFocus: '#0068FF',
        strokeInformation: {
          strong: '#1A74A8CC',
          weak: '#1A74A833',
        },
        strokeInverse: {
          disabled: '#FFFFFF1F',
          strong: '#FFFFFF99',
          weak: '#FFFFFF1F',
        },
        strokeSelected: '#0068FF',
        strokeStrong: '#000D4D73',
        strokeSuccess: {
          strong: '#067A57CC',
          weak: '#067A5733',
        },
        strokeWarning: {
          strong: '#8F6C1ACC',
          weak: '#8F6C1A33',
        },
        strokeWeak: '#0011661A',
        textBrand: '#0068FF',
        textDisabled: '#000D4D73',
        textError: '#C73A3A',
        textInverse: {
          disabled: '#FFFFFF1F',
          strong: '#FFFFFF',
          weak: '#FFFFFFC7',
        },
        textStrong: '#000626E6',
        textWeak: '#000833A6',
      },
      gridTemplateColumns: {
        16: 'repeat(16, minmax(0, 1fr))',
      },
      gridColumn: {
        'span-13': 'span 13 / span 13',
        'span-14': 'span 14 / span 14',
      },
      fontFamily: {
        sans: ['-apple-system', 'BlinkMacSystemFont', "'Segoe UI'", 'Roboto', "'Helvetica Neue'", 'Helvetica', "'PingFang SC'", "'Hiragino Sans GB'", "'Microsoft YaHei'", 'SimSun', 'sans-serif'],
      },
    },
  },
  plugins: [require('daisyui'), require('@tailwindcss/typography')],
}
