module Pages.Bots.BotFixtures (
  -- * Slack Fixtures
  slackInteraction,
  slackEventCallback,
  slackThreadedEvent,
  slackActionPayload,

  -- * Discord Fixtures
  discordPingPayload,
  discordCommandInteraction,
  discordThreadInteraction,

  -- * WhatsApp Fixtures
  twilioWhatsAppMessage,
  twilioWhatsAppPrompt,
  twilioWhatsAppDashboard,

  -- * Test Phone Number Helper
  getTestPhoneNumber,
) where

import Data.Aeson qualified as AE
import Data.Aeson.QQ (aesonQQ)
import Data.ByteString qualified as BS
import Data.Text qualified as T
import Pages.Bots.Slack qualified as Slack
import Pages.Bots.Whatsapp qualified as Whatsapp
import Pkg.TestUtils (TestResources (..))
import Relude
import System.Config (AuthContext (..), EnvConfig (..))


-- * Slack Fixtures


slackInteraction :: Text -> Text -> Text -> Slack.SlackInteraction
slackInteraction cmd query teamId =
  Slack.SlackInteraction
    teamId  -- team_id
    cmd  -- command
    query  -- text
    ("https://hooks.slack.com/commands/" <> teamId <> "/response")  -- response_url
    ("trigger_" <> teamId)  -- trigger_id
    "C_TEST_CHANNEL"  -- channel_id
    "general"  -- channel_name
    "U_TEST_USER"  -- user_id


slackEventCallback :: Text -> Text -> Text -> Text -> Maybe Text -> AE.Value
slackEventCallback teamId channelId userText ts threadTsM =
  [aesonQQ|{
    "type": "event_callback",
    "token": "test_token",
    "team_id": #{teamId},
    "api_app_id": "A_TEST_APP",
    "event": {
      "type": "message",
      "user": "U_TEST_USER",
      "text": #{userText},
      "ts": #{ts},
      "channel": #{channelId},
      "event_ts": #{ts},
      "thread_ts": #{maybeToJSON threadTsM}
    },
    "event_id": "Ev_TEST",
    "event_time": 1700000000
  }|]
  where
    maybeToJSON :: Maybe Text -> AE.Value
    maybeToJSON = maybe AE.Null AE.String


slackThreadedEvent :: Text -> Text -> Text -> Text -> Text -> AE.Value
slackThreadedEvent teamId channelId userText ts threadTs =
  slackEventCallback teamId channelId userText ts (Just threadTs)


slackActionPayload :: Text -> AE.Value
slackActionPayload actionType =
  [aesonQQ|{
    "type": #{actionType},
    "token": "test_token",
    "trigger_id": "trigger_123",
    "view": {
      "private_metadata": "C_TEST___proj123",
      "blocks": [],
      "id": "view_123",
      "state": null
    },
    "actions": null,
    "user": {
      "id": "U_TEST_USER",
      "username": "testuser",
      "team_id": "T_TEST"
    }
  }|]


-- * Discord Fixtures


discordPingPayload :: BS.ByteString
discordPingPayload = toStrict $ AE.encode [aesonQQ|{"type": 1, "id": "123", "token": "tok"}|]


discordCommandInteraction :: Text -> Text -> BS.ByteString
discordCommandInteraction commandName query =
  toStrict
    $ AE.encode
      [aesonQQ|{
    "type": 2,
    "id": "interaction_123",
    "token": "interaction_token",
    "data": {
      "name": #{commandName},
      "options": [{"name": "question", "value": #{query}}]
    },
    "channel_id": "chan_123",
    "guild_id": "guild_test_123",
    "channel": null
  }|]


discordThreadInteraction :: Text -> Text -> Text -> BS.ByteString
discordThreadInteraction commandName query threadId =
  toStrict
    $ AE.encode
      [aesonQQ|{
    "type": 2,
    "id": "interaction_123",
    "token": "interaction_token",
    "data": {
      "name": #{commandName},
      "options": [{"name": "question", "value": #{query}}]
    },
    "channel_id": #{threadId},
    "guild_id": "guild_test_123",
    "channel": {
      "id": #{threadId},
      "name": "test-thread",
      "guild_id": "guild_test_123",
      "type": 11,
      "parent_id": "chan_123",
      "owner_id": "U_TEST",
      "thread_metadata": null
    }
  }|]


-- * WhatsApp Fixtures


getTestPhoneNumber :: TestResources -> Text
getTestPhoneNumber tr = fromMaybe "+2348161115653" (tr.trATCtx.config.testPhoneNumber)


twilioWhatsAppMessage :: TestResources -> Text -> Text -> Text -> Whatsapp.TwilioWhatsAppMessage
twilioWhatsAppMessage tr from to body =
  Whatsapp.TwilioWhatsAppMessage
    testMessageSid  -- messageSid (unique per message, generated by Twilio)
    testMessageSid  -- smsSid
    testMessageSid  -- smsMessageSid
    (tr.trATCtx.config.twilioAccountSid)  -- accountSid from config
    Nothing  -- messagingServiceSid
    from  -- from
    to  -- to
    body  -- body
    0  -- numMedia
    1  -- numSegments
    (Just "Test User")  -- profileName
    (Just $ stripWhatsAppPrefix from)  -- waId (phone number without whatsapp: prefix and +)
    Nothing  -- forwarded
    Nothing  -- frequentlyForwarded
    Nothing  -- buttonText
  where
    stripWhatsAppPrefix t = fromMaybe t $ T.stripPrefix "whatsapp:+" t <|> T.stripPrefix "whatsapp:" t
    testMessageSid = "SMa1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4"  -- realistic Twilio SID format


twilioWhatsAppPrompt :: TestResources -> Text -> Text -> Whatsapp.TwilioWhatsAppMessage
twilioWhatsAppPrompt tr fromNumber query =
  twilioWhatsAppMessage tr ("whatsapp:" <> fromNumber) ("whatsapp:" <> (tr.trATCtx.config.whatsappFromNumber)) query


twilioWhatsAppDashboard :: TestResources -> Text -> Whatsapp.TwilioWhatsAppMessage
twilioWhatsAppDashboard tr fromNumber =
  twilioWhatsAppMessage tr ("whatsapp:" <> fromNumber) ("whatsapp:" <> tr.trATCtx.config.whatsappFromNumber) "/dashboard"
