BEGIN;
ALTER TABLE projects.projects ADD COLUMN IF NOT EXISTS endpoint_alerts BOOL NOT NULL DEFAULT TRUE;
ALTER TABLE projects.projects ADD COLUMN IF NOT EXISTS error_alerts BOOL NOT NULL DEFAULT TRUE;
COMMIT; 