BEGIN; 
ALTER TABLE apis.reports ADD COLUMN IF NOT EXISTS start_time TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT current_timestamp;
ALTER TABLE apis.reports ADD COLUMN IF NOT EXISTS end_time TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT current_timestamp;
COMMIT;