workspace = { members = ["target/debug/build/reflexive-eb3dcc54ed134ea3/out/hs-bindgen/sandbox"] }
[package]
name = "rust-interop"
version = "0.1.0"
edition = "2021"

[dependencies]
hs-bindgen = { version = "0.9.0", features = ["full"] }

[lib]
crate-type = ["staticlib", "cdylib"]
